apiVersion: apps/v1
kind: Deployment
metadata:
  name: anakosmos
  namespace: default
  labels:
    app: anakosmos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anakosmos
  template:
    metadata:
      labels:
        app: anakosmos
    spec:
      serviceAccountName: anakosmos-sa
      containers:
      - name: anakosmos
        image: localhost/anakosmos:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: anakosmos
  namespace: default
spec:
  selector:
    app: anakosmos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
