apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube3d-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube3d-cluster-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube3d-cluster-reader-binding
subjects:
- kind: ServiceAccount
  name: kube3d-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: kube3d-cluster-reader
  apiGroup: rbac.authorization.k8s.io
